import {
  ACCESS_DENIED_ROUTE,
  ALL_APP_PERMISSIONS,
  APP_PERMISSIONS,
  ROLE_PERMISSIONS,
  firstAccessibleRouteForRole,
  isAppPermission,
} from './rbac.config';

describe('RBAC configuration', () => {
  it('mirrors the backend permission vocabulary without duplicates', () => {
    expect(ALL_APP_PERMISSIONS.length).toBe(39);
    expect(new Set(ALL_APP_PERMISSIONS).size).toBe(39);
    expect(isAppPermission(APP_PERMISSIONS.USERS_MANAGE)).toBeTrue();
    expect(isAppPermission('USERS_READ')).toBeFalse();
  });

  it('gives OWNER and ADMIN every permission, including users and audit', () => {
    expect(ROLE_PERMISSIONS.OWNER).toEqual(ALL_APP_PERMISSIONS);
    expect(ROLE_PERMISSIONS.ADMIN).toEqual(ALL_APP_PERMISSIONS);
    expect(ROLE_PERMISSIONS.OWNER).toContain(APP_PERMISSIONS.USERS_MANAGE);
    expect(ROLE_PERMISSIONS.ADMIN).toContain(APP_PERMISSIONS.AUDIT_READ);
  });

  it('mirrors the backend FINANCEIRO permissions', () => {
    expect(ROLE_PERMISSIONS.FINANCEIRO).toEqual([
      APP_PERMISSIONS.PEOPLE_READ,
      APP_PERMISSIONS.COMPANIES_READ,
      APP_PERMISSIONS.BANK_ACCOUNTS_READ,
      APP_PERMISSIONS.BANK_ACCOUNTS_WRITE,
      APP_PERMISSIONS.DEVELOPMENTS_READ,
      APP_PERMISSIONS.UNITS_READ,
      APP_PERMISSIONS.PRICES_READ,
      APP_PERMISSIONS.INVESTMENTS_READ,
      APP_PERMISSIONS.INVESTMENTS_WRITE,
      APP_PERMISSIONS.RETURNS_READ,
      APP_PERMISSIONS.RETURNS_WRITE,
      APP_PERMISSIONS.DOCUMENTS_READ,
      APP_PERMISSIONS.INTERACTIONS_READ,
      APP_PERMISSIONS.DASHBOARD_READ,
      APP_PERMISSIONS.REPORTS_EXPORT,
      APP_PERMISSIONS.FINANCE_READ,
      APP_PERMISSIONS.FINANCE_WRITE,
      APP_PERMISSIONS.MONETARY_INDEX_READ,
      APP_PERMISSIONS.MONETARY_INDEX_CREATE,
      APP_PERMISSIONS.MONETARY_INDEX_UPDATE,
      APP_PERMISSIONS.MONETARY_INDEX_VALUE_READ,
      APP_PERMISSIONS.MONETARY_INDEX_VALUE_CREATE,
      APP_PERMISSIONS.MONETARY_INDEX_VALUE_UPDATE,
      APP_PERMISSIONS.RECEIVABLE_ADJUSTMENT_PREVIEW,
      APP_PERMISSIONS.RECEIVABLE_ADJUSTMENT_CREATE,
      APP_PERMISSIONS.RECEIVABLE_ADJUSTMENT_READ,
    ]);
  });

  it('mirrors the backend COMERCIAL, OPERACIONAL and LEITURA permissions', () => {
    expect(ROLE_PERMISSIONS.COMERCIAL).toEqual([
      APP_PERMISSIONS.PEOPLE_READ,
      APP_PERMISSIONS.PEOPLE_WRITE,
      APP_PERMISSIONS.COMPANIES_READ,
      APP_PERMISSIONS.DEVELOPMENTS_READ,
      APP_PERMISSIONS.UNITS_READ,
      APP_PERMISSIONS.PRICES_READ,
      APP_PERMISSIONS.DOCUMENTS_READ,
      APP_PERMISSIONS.DOCUMENTS_WRITE,
      APP_PERMISSIONS.INTERACTIONS_READ,
      APP_PERMISSIONS.INTERACTIONS_WRITE,
      APP_PERMISSIONS.CRM_READ,
      APP_PERMISSIONS.CRM_WRITE,
      APP_PERMISSIONS.SALES_READ,
      APP_PERMISSIONS.SALES_WRITE,
    ]);
    expect(ROLE_PERMISSIONS.OPERACIONAL).toEqual([
      APP_PERMISSIONS.PEOPLE_READ,
      APP_PERMISSIONS.COMPANIES_READ,
      APP_PERMISSIONS.DEVELOPMENTS_READ,
      APP_PERMISSIONS.DEVELOPMENTS_WRITE,
      APP_PERMISSIONS.UNITS_READ,
      APP_PERMISSIONS.UNITS_WRITE,
      APP_PERMISSIONS.PRICES_READ,
      APP_PERMISSIONS.PRICES_WRITE,
      APP_PERMISSIONS.DOCUMENTS_READ,
      APP_PERMISSIONS.DOCUMENTS_WRITE,
      APP_PERMISSIONS.INTERACTIONS_READ,
      APP_PERMISSIONS.INTERACTIONS_WRITE,
      APP_PERMISSIONS.CRM_READ,
    ]);
    expect(ROLE_PERMISSIONS.LEITURA).toEqual([
      APP_PERMISSIONS.PEOPLE_READ,
      APP_PERMISSIONS.COMPANIES_READ,
      APP_PERMISSIONS.DEVELOPMENTS_READ,
      APP_PERMISSIONS.UNITS_READ,
      APP_PERMISSIONS.PRICES_READ,
      APP_PERMISSIONS.DOCUMENTS_READ,
      APP_PERMISSIONS.INTERACTIONS_READ,
      APP_PERMISSIONS.CRM_READ,
    ]);
  });

  it('selects an accessible post-login route for every role', () => {
    expect(firstAccessibleRouteForRole('OWNER')).toBe('/dashboard');
    expect(firstAccessibleRouteForRole('ADMIN')).toBe('/dashboard');
    expect(firstAccessibleRouteForRole('FINANCEIRO')).toBe('/dashboard');
    expect(firstAccessibleRouteForRole('COMERCIAL')).toBe('/crm');
    expect(firstAccessibleRouteForRole('OPERACIONAL')).toBe('/crm');
    expect(firstAccessibleRouteForRole('LEITURA')).toBe('/crm');
    expect(firstAccessibleRouteForRole(null)).toBe(ACCESS_DENIED_ROUTE);
  });
});
